// <auto-generated />
namespace UMS_Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RoleBasedMenuEdited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleBasedMenuEdited));
        
        string IMigrationMetadata.Id
        {
            get { return "202004242112544_RoleBasedMenuEdited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
